name: dotfiles

path: .

windows:
  - name: code
    panes:
      - flex: 2
        commands:
          - command: ^$env.EDITOR
      - flex: 1
        commands:
          - command: ^opencode
            args:
              - --port

  - name: misc
    panes:
      - flex: 1
      - flex: 1
