name: dotfiles

path: .

startup:
  - command: sh
    args:
      - -c
      - 'echo "hello again"'

windows:
  - name: code
    panes:
      - commands:
          - command: nvim

  - name: misc
    panes:
      - flex: 1
      - flex: 1
